REQUIRED_PERMISSIONS = [
    "s3:ListAllMyBuckets",
    "s3:GetBucketPublicAccessBlock",
    "s3:GetBucketAcl",
    "s3:GetBucketEncryption",
    "s3:GetBucketVersioning",
    "s3:GetBucketLogging",
    "ec2:DescribeSecurityGroups",
    "ec2:DescribeInstances",
    "ec2:DescribeRegions",
    "ec2:DescribeVpcs",
    "ec2:DescribeFlowLogs",
    "rds:DescribeDBInstances",
    "iam:GetAccountSummary",
    "iam:GenerateCredentialReport",
    "iam:GetCredentialReport",
    "iam:ListUsers",
    "iam:ListPolicies",
    "iam:GetPolicyVersion",
    "iam:ListAttachedUserPolicies",
    "iam:GetAccountPasswordPolicy",
    "lambda:ListFunctions",
    "cloudtrail:DescribeTrails",
    "logs:DescribeLogGroups",
    "sts:GetCallerIdentity",
]

READ_ONLY_POLICY = {
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "CloudWatchReadOnly",
            "Effect": "Allow",
            "Action": [
                "s3:List*",
                "s3:GetBucket*",
                "ec2:Describe*",
                "rds:Describe*",
                "iam:List*",
                "iam:Get*",
                "iam:GenerateCredentialReport",
                "lambda:List*",
                "lambda:Get*",
                "cloudtrail:Describe*",
                "cloudtrail:GetTrailStatus",
                "logs:Describe*",
                "cloudwatch:DescribeAlarms",
                "config:Describe*",
                "sts:GetCallerIdentity",
            ],
            "Resource": "*",
        }
    ],
}
